// Package repolink provides shared helpers for linking repository
// directories into the notizen source tree and for writing generated
// Sphinx index files safely.
//
// The helpers assume notizen is the only writer: the guards protect
// against state that exists before a command runs (hand-written files,
// dangerous names, symlink detours), not against other processes
// modifying the involved trees concurrently. Operations are not
// transactional: preflight-detectable errors stop before any change,
// but a later I/O failure can leave the link updated with only some
// index files written. Each individual file write is atomic.
package repolink

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
)

// Action describes what EnsureSymlink did to the link path.
type Action string

const (
	ActionCreated Action = "created"
	ActionSkipped Action = "skipped"
	ActionUpdated Action = "updated"
)

// GeneratedMarker is the first line of every index file written by
// WriteIndex. Files without it are treated as hand-written and are never
// overwritten unless force is set. It is a reStructuredText comment so it
// stays invisible wherever the generated toctree directives work.
const GeneratedMarker = ".. Generated by notizen. DO NOT EDIT."

// NormalizeDir resolves path to an absolute, symlink-free, existing
// directory. Callers normalize every root they work with so that symlink
// targets and the physical comparisons in PathsOverlap are stable
// regardless of the working directory or symlinked parents.
func NormalizeDir(path string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	resolved, err := filepath.EvalSymlinks(abs)
	if err != nil {
		return "", err
	}
	info, err := os.Stat(resolved)
	if err != nil {
		return "", err
	}
	if !info.IsDir() {
		return "", fmt.Errorf("%s is not a directory", resolved)
	}
	return resolved, nil
}

// ResolveRepoName returns the repository name for repoPath. A non-empty
// nameOverride wins; otherwise the name comes from `git remote get-url
// origin` with any .git suffix stripped. Either way the final name must be
// a plain directory name, so that the link directory cannot escape or
// collapse into its parent (e.g. via "..").
func ResolveRepoName(repoPath, nameOverride string) (string, error) {
	if nameOverride != "" {
		name := filepath.Base(nameOverride)
		if err := validateRepoName(name); err != nil {
			return "", err
		}
		return name, nil
	}
	cmd := exec.Command("git", "remote", "get-url", "origin")
	cmd.Dir = repoPath
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("could not get git remote — use --name to specify repo name: %w", err)
	}
	url := strings.TrimSpace(string(out))
	name := strings.TrimSuffix(filepath.Base(url), ".git")
	if err := validateRepoName(name); err != nil {
		return "", err
	}
	return name, nil
}

func validateRepoName(name string) error {
	if name == "" || name == "." || name == ".." || strings.ContainsRune(name, filepath.Separator) {
		return fmt.Errorf("invalid repo name %q — use --name to specify a plain directory name", name)
	}
	return nil
}

// ResolveUnder inspects base/components... element by element. base must be
// an existing, normalized directory. All components are validated before any
// filesystem access so that an invalid element after a missing one cannot
// slip through. The returned path is always the full candidate
// filepath.Join(base, components...); the boolean reports whether every
// element exists as a real directory. A symlink or regular file anywhere on
// the way is an error, as is any Lstat failure other than "not exist".
func ResolveUnder(base string, components ...string) (string, bool, error) {
	for _, c := range components {
		if c == "" || c == "." || c == ".." || filepath.IsAbs(c) || strings.ContainsRune(c, filepath.Separator) {
			return "", false, fmt.Errorf("invalid path component %q under %s", c, base)
		}
	}
	full := filepath.Join(append([]string{base}, components...)...)
	cursor := base
	for _, c := range components {
		cursor = filepath.Join(cursor, c)
		info, err := os.Lstat(cursor)
		if errors.Is(err, os.ErrNotExist) || errors.Is(err, syscall.ENOTDIR) {
			return full, false, nil
		}
		if err != nil {
			return "", false, fmt.Errorf("failed to inspect %s: %w", cursor, err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return "", false, fmt.Errorf("%s is a symlink — refusing to traverse it", cursor)
		}
		if !info.IsDir() {
			return "", false, fmt.Errorf("%s is not a directory", cursor)
		}
	}
	return full, true, nil
}

// EnsureSymlink makes linkDir a symlink pointing at target, creating parent
// directories as needed. A missing path is created; a symlink already
// pointing at target is left alone; a symlink pointing elsewhere is replaced
// atomically. A real directory is an error: automatic migration of its
// contents was removed because it cannot be made safe against collisions
// and partial failures.
func EnsureSymlink(linkDir, target string) (Action, error) {
	if err := os.MkdirAll(filepath.Dir(linkDir), 0o755); err != nil {
		return "", fmt.Errorf("failed to create parent directory: %w", err)
	}
	info, err := os.Lstat(linkDir)
	if errors.Is(err, os.ErrNotExist) {
		if err := os.Symlink(target, linkDir); err != nil {
			return "", fmt.Errorf("failed to create symlink: %w", err)
		}
		return ActionCreated, nil
	}
	if err != nil {
		return "", fmt.Errorf("failed to stat path: %w", err)
	}
	switch {
	case info.Mode()&os.ModeSymlink != 0:
		current, err := os.Readlink(linkDir)
		if err != nil {
			return "", err
		}
		if current == target {
			return ActionSkipped, nil
		}
		if err := replaceSymlink(linkDir, target); err != nil {
			return "", err
		}
		return ActionUpdated, nil
	case info.IsDir():
		return "", fmt.Errorf("%s is a real directory — move its contents into %s manually, remove it, then re-run", linkDir, target)
	default:
		return "", fmt.Errorf("%s already exists and is not a symlink", linkDir)
	}
}

// replaceSymlink repoints linkDir by creating a temporary symlink next to it
// and renaming over the old one, so the old link survives a failed creation.
func replaceSymlink(linkDir, target string) error {
	// os.CreateTemp only reserves a unique name here: the file is removed
	// and the name reused for the symlink, which is safe under the
	// package's single-writer assumption.
	tmp, err := os.CreateTemp(filepath.Dir(linkDir), filepath.Base(linkDir)+".tmp-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Remove(tmpName); err != nil {
		return err
	}
	if err := os.Symlink(target, tmpName); err != nil {
		return err
	}
	if err := os.Rename(tmpName, linkDir); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	return nil
}

// ListMarkdownFiles returns the names (without the .md suffix) of markdown
// files directly inside dir, excluding index files and subdirectories. On
// case-insensitive filesystems a differently-spelled index (e.g. Index.md)
// is the same file as the one WriteIndex writes, so entries are also
// compared physically against dir/index.md.
func ListMarkdownFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	indexInfo, err := os.Stat(filepath.Join(dir, "index.md"))
	if err != nil {
		indexInfo = nil
	}
	var files []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") || e.Name() == "index.md" {
			continue
		}
		if indexInfo != nil {
			info, err := e.Info()
			if err != nil {
				return nil, err
			}
			if os.SameFile(indexInfo, info) {
				continue
			}
		}
		files = append(files, strings.TrimSuffix(e.Name(), ".md"))
	}
	return files, nil
}

// walkedPath is the element-wise Lstat walk of an absolute path.
// infos[i] is the Lstat of the prefix holding i components (infos[0] is the
// filesystem root); only prefixes that are existing real directories are
// walked, so len(infos) == resolved+1. Components at index >= resolved are
// unresolved: missing, or placed at/behind a symlink or regular file.
type walkedPath struct {
	names    []string
	infos    []os.FileInfo
	resolved int
}

func walkPath(path string) (walkedPath, error) {
	clean := filepath.Clean(path)
	if !filepath.IsAbs(clean) {
		return walkedPath{}, fmt.Errorf("path %q must be absolute", path)
	}
	var w walkedPath
	if clean != string(filepath.Separator) {
		w.names = strings.Split(strings.TrimPrefix(clean, string(filepath.Separator)), string(filepath.Separator))
	}
	rootInfo, err := os.Lstat(string(filepath.Separator))
	if err != nil {
		return walkedPath{}, err
	}
	w.infos = append(w.infos, rootInfo)
	cursor := string(filepath.Separator)
	for _, name := range w.names {
		cursor = filepath.Join(cursor, name)
		info, err := os.Lstat(cursor)
		if errors.Is(err, os.ErrNotExist) || errors.Is(err, syscall.ENOTDIR) {
			break
		}
		if err != nil {
			return walkedPath{}, fmt.Errorf("failed to inspect %s: %w", cursor, err)
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
			break
		}
		w.infos = append(w.infos, info)
		w.resolved++
	}
	return w, nil
}

// PathsOverlap reports whether the placements of two absolute paths are the
// same or one contains the other. It compares directory-entry positions, not
// symlink resolutions: the walk stops at the first symlink, so a link that
// already points at the other path does not count as overlap, while a link
// placed inside the other path does.
//
// The paths are decomposed into their deepest physically identical ancestor
// (found via os.SameFile across the two walks) plus residual elements. The
// residuals overlap only when one is an element-wise prefix of the other,
// where two existing elements must be the same file, an existing element
// never matches an unresolved one, and two unresolved elements match by
// exact or case-insensitive name. The case-insensitive fallback errs on the
// safe side for filesystems like APFS, where differently-spelled names can
// denote the same entry.
func PathsOverlap(a, b string) (bool, error) {
	wa, err := walkPath(a)
	if err != nil {
		return false, err
	}
	wb, err := walkPath(b)
	if err != nil {
		return false, err
	}

	// The deepest SameFile pair across the two ancestor chains. Both paths
	// are absolute, so at worst the pair is the filesystem root itself.
	ca, cb := -1, -1
	for i := wa.resolved; i >= 0 && ca < 0; i-- {
		for j := wb.resolved; j >= 0; j-- {
			if os.SameFile(wa.infos[i], wb.infos[j]) {
				ca, cb = i, j
				break
			}
		}
	}
	if ca < 0 {
		return false, nil
	}

	n := min(len(wa.names)-ca, len(wb.names)-cb)
	for k := range n {
		pa, pb := ca+k, cb+k
		existsA, existsB := pa < wa.resolved, pb < wb.resolved
		switch {
		case existsA && existsB:
			if !os.SameFile(wa.infos[pa+1], wb.infos[pb+1]) {
				return false, nil
			}
		case existsA != existsB:
			return false, nil
		default:
			na, nb := wa.names[pa], wb.names[pb]
			if na != nb && !strings.EqualFold(na, nb) {
				return false, nil
			}
		}
	}
	return true, nil
}

// CheckIndexWritable reports whether WriteIndex may write to path: a missing
// file is fine, anything that is not a regular file is refused, and an
// existing regular file must start with GeneratedMarker unless force is set.
// Callers run it for every planned path during preflight and join the
// failures, so that --force users see the full list of affected files.
func CheckIndexWritable(path string, force bool) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("failed to inspect %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s exists and is not a regular file — refusing to overwrite", path)
	}
	if force {
		return nil
	}
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()
	scanner := bufio.NewScanner(f)
	if scanner.Scan() && scanner.Text() == GeneratedMarker {
		return nil
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	return fmt.Errorf("%s was not generated by notizen — re-run with --force to overwrite it", path)
}

// WriteIndex writes GeneratedMarker, a blank line, and content to path under
// the CheckIndexWritable rules. The write goes through a temp file in the
// same directory (synced, then renamed) so an existing file is never left
// truncated. New files get mode 0644; updates keep the existing mode.
func WriteIndex(path string, content []byte, force bool) error {
	if err := CheckIndexWritable(path, force); err != nil {
		return err
	}
	perm := os.FileMode(0o644)
	if info, err := os.Lstat(path); err == nil {
		perm = info.Mode().Perm()
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
	}()
	if _, err := tmp.WriteString(GeneratedMarker + "\n\n"); err != nil {
		return err
	}
	if _, err := tmp.Write(content); err != nil {
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		return err
	}
	if err := tmp.Sync(); err != nil {
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}
