package main

import (
	"fmt"
	"path/filepath"

	"github.com/peacock0803sz/notizen/internal/superpowers"
	"github.com/spf13/cobra"
)

var superpowersCmd = &cobra.Command{
	Use:   "superpowers <repo-path>",
	Short: "Link repo superpowers docs into notizen documentation",
	Args:  cobra.ExactArgs(1),
	RunE:  runSuperpowers,
}

func init() {
	superpowersCmd.Flags().StringP("name", "n", "", "Override auto-detected repo name")
	superpowersCmd.Flags().Bool("force", false, "Overwrite index files not generated by notizen")
}

func runSuperpowers(cmd *cobra.Command, args []string) error {
	root, err := ensureRoot()
	if err != nil {
		return err
	}

	repoPath := args[0]
	name, _ := cmd.Flags().GetString("name")
	force, _ := cmd.Flags().GetBool("force")
	sourceDir := filepath.Join(root, "source")

	msg, err := superpowers.Link(sourceDir, repoPath, name, force)
	if err != nil {
		return err
	}
	_, err = fmt.Fprintln(cmd.OutOrStdout(), msg)
	return err
}
